// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ip_to_df
DataFrame ip_to_df(std::list < std::vector < std::string > > x);
RcppExport SEXP rgeolocate_ip_to_df(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::list < std::vector < std::string > > >::type x(xSEXP);
    __result = Rcpp::wrap(ip_to_df(x));
    return __result;
END_RCPP
}
// freegeoip_to_df
DataFrame freegeoip_to_df(std::list < std::vector < std::string > > x);
RcppExport SEXP rgeolocate_freegeoip_to_df(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::list < std::vector < std::string > > >::type x(xSEXP);
    __result = Rcpp::wrap(freegeoip_to_df(x));
    return __result;
END_RCPP
}
// telize_to_df
DataFrame telize_to_df(std::list < std::vector < std::string > > x);
RcppExport SEXP rgeolocate_telize_to_df(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::list < std::vector < std::string > > >::type x(xSEXP);
    __result = Rcpp::wrap(telize_to_df(x));
    return __result;
END_RCPP
}
// maxmind_
List maxmind_(CharacterVector ips, const char* file, std::vector < std::string > fields);
RcppExport SEXP rgeolocate_maxmind_(SEXP ipsSEXP, SEXP fileSEXP, SEXP fieldsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type ips(ipsSEXP);
    Rcpp::traits::input_parameter< const char* >::type file(fileSEXP);
    Rcpp::traits::input_parameter< std::vector < std::string > >::type fields(fieldsSEXP);
    __result = Rcpp::wrap(maxmind_(ips, file, fields));
    return __result;
END_RCPP
}
