// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ip_to_df
DataFrame ip_to_df(List x);
RcppExport SEXP rgeolocate_ip_to_df(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ip_to_df(x));
    return rcpp_result_gen;
END_RCPP
}
// maxmind_
List maxmind_(CharacterVector ips, const char* file, std::vector < std::string > fields);
RcppExport SEXP rgeolocate_maxmind_(SEXP ipsSEXP, SEXP fileSEXP, SEXP fieldsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ips(ipsSEXP);
    Rcpp::traits::input_parameter< const char* >::type file(fileSEXP);
    Rcpp::traits::input_parameter< std::vector < std::string > >::type fields(fieldsSEXP);
    rcpp_result_gen = Rcpp::wrap(maxmind_(ips, file, fields));
    return rcpp_result_gen;
END_RCPP
}
// ip2location_
List ip2location_(CharacterVector ips, CharacterVector fields, std::string file, bool use_memory);
RcppExport SEXP rgeolocate_ip2location_(SEXP ipsSEXP, SEXP fieldsSEXP, SEXP fileSEXP, SEXP use_memorySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ips(ipsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type fields(fieldsSEXP);
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< bool >::type use_memory(use_memorySEXP);
    rcpp_result_gen = Rcpp::wrap(ip2location_(ips, fields, file, use_memory));
    return rcpp_result_gen;
END_RCPP
}
