# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ip_to_df <- function(x) {
    .Call('rgeolocate_ip_to_df', PACKAGE = 'rgeolocate', x)
}

freegeoip_to_df <- function(x) {
    .Call('rgeolocate_freegeoip_to_df', PACKAGE = 'rgeolocate', x)
}

telize_to_df <- function(x) {
    .Call('rgeolocate_telize_to_df', PACKAGE = 'rgeolocate', x)
}

maxmind_ <- function(ips, file, fields) {
    .Call('rgeolocate_maxmind_', PACKAGE = 'rgeolocate', ips, file, fields)
}

